### ISSUE TITLE
how can i deal with this dependancy problem

### ISSUE THREAD

**Issue by lewisMachilika** [Arbazkhan4712/Voice-Translator#1]
Traceback (most recent call last):
  File "/root/anaconda3/envs/tensorflow_env/lib/python3.7/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/root/anaconda3/envs/tensorflow_env/lib/python3.7/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trans.py", line 5, in <module>
    engine = pyttsx3.init('sapi5')
  File "/root/anaconda3/envs/tensorflow_env/lib/python3.7/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/root/anaconda3/envs/tensorflow_env/lib/python3.7/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/root/anaconda3/envs/tensorflow_env/lib/python3.7/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/root/anaconda3/envs/tensorflow_env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/anaconda3/envs/tensorflow_env/lib/python3.7/site-packages/pyttsx3/drivers/sapi5.py", line 1, in <module>
    import comtypes.client  # Importing comtypes.client will make the gen subpackage
  File "/root/anaconda3/envs/tensorflow_env/lib/python3.7/site-packages/comtypes/__init__.py", line 23, in <module>
    from _ctypes import COMError
ImportError: cannot import name 'COMError' from '_ctypes' (/root/anaconda3/envs/tensorflow_env/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so)

**Comment by Arbazkhan4712** [comment]
this program works on windows and if you want to use it on Ubuntu you need to install espeak
